export const kpis = [
  {
    label: "Total Revenue",
    value: "₹12,84,500",
    change: "+12.4%",
    trend: "up" as const,
    hint: "vs last month",
  },
  {
    label: "Invoices Raised",
    value: "1,284",
    change: "+8.1%",
    trend: "up" as const,
    hint: "this month",
  },
  {
    label: "Outstanding",
    value: "₹1,42,800",
    change: "-4.2%",
    trend: "down" as const,
    hint: "receivables",
  },
  {
    label: "GST Collected",
    value: "₹2,31,210",
    change: "+6.7%",
    trend: "up" as const,
    hint: "current cycle",
  },
];

export const recentInvoices = [
  {
    id: "INV-2041",
    customer: "Sharma Traders",
    date: "12 Jul 2026",
    amount: "₹24,500",
    status: "Paid",
  },
  {
    id: "INV-2040",
    customer: "Raj Medical Store",
    date: "12 Jul 2026",
    amount: "₹8,120",
    status: "Pending",
  },
  {
    id: "INV-2039",
    customer: "Krishna Hardware",
    date: "11 Jul 2026",
    amount: "₹56,900",
    status: "Paid",
  },
  {
    id: "INV-2038",
    customer: "Modern Garments",
    date: "11 Jul 2026",
    amount: "₹12,400",
    status: "Overdue",
  },
  {
    id: "INV-2037",
    customer: "Deep Electricals",
    date: "10 Jul 2026",
    amount: "₹34,780",
    status: "Paid",
  },
  {
    id: "INV-2036",
    customer: "Balaji Furniture",
    date: "10 Jul 2026",
    amount: "₹1,12,000",
    status: "Draft",
  },
];

export const customers = [
  {
    id: "C-102",
    name: "Sharma Traders",
    gstin: "27ABCDE1234F1Z5",
    phone: "+91 98765 43210",
    city: "Mumbai",
    balance: "₹0",
    type: "B2B",
  },
  {
    id: "C-103",
    name: "Raj Medical Store",
    gstin: "24AABCU9603R1ZL",
    phone: "+91 90123 45678",
    city: "Surat",
    balance: "₹8,120",
    type: "B2B",
  },
  {
    id: "C-104",
    name: "Krishna Hardware",
    gstin: "29AAACR5055K1Z1",
    phone: "+91 99887 66554",
    city: "Bengaluru",
    balance: "₹0",
    type: "B2B",
  },
  {
    id: "C-105",
    name: "Modern Garments",
    gstin: "07AAECS1234A1Z1",
    phone: "+91 90000 11122",
    city: "Delhi",
    balance: "₹12,400",
    type: "B2B",
  },
  {
    id: "C-106",
    name: "Walk-in Customer",
    gstin: "—",
    phone: "—",
    city: "Local",
    balance: "₹0",
    type: "B2C",
  },
];

export const suppliers = [
  {
    id: "S-11",
    name: "Bharat Distributors",
    gstin: "27AAACB2894G1Z0",
    phone: "+91 98200 11122",
    city: "Pune",
    payable: "₹42,300",
  },
  {
    id: "S-12",
    name: "Sunrise Wholesale",
    gstin: "24AAACS1122F1Z5",
    phone: "+91 97600 33221",
    city: "Ahmedabad",
    payable: "₹0",
  },
  {
    id: "S-13",
    name: "MediSource India",
    gstin: "29AAACM4455K1Z1",
    phone: "+91 98800 66655",
    city: "Bengaluru",
    payable: "₹18,900",
  },
];

export const products = [
  {
    id: "P-2001",
    name: "Paracetamol 500mg",
    sku: "MED-PARA-500",
    category: "Medicines",
    price: "₹18",
    gst: "12%",
    stock: 240,
    unit: "Strip",
  },
  {
    id: "P-2002",
    name: "Cotton T-Shirt (M)",
    sku: "GRM-TSH-M",
    category: "Garments",
    price: "₹399",
    gst: "5%",
    stock: 42,
    unit: "Pcs",
  },
  {
    id: "P-2003",
    name: "LED Bulb 9W",
    sku: "ELC-LED-9",
    category: "Electrical",
    price: "₹120",
    gst: "18%",
    stock: 8,
    unit: "Pcs",
  },
  {
    id: "P-2004",
    name: "Steel Hinges 4in",
    sku: "HDW-HNG-4",
    category: "Hardware",
    price: "₹65",
    gst: "18%",
    stock: 320,
    unit: "Pcs",
  },
  {
    id: "P-2005",
    name: "Office Chair",
    sku: "FRN-CHR-01",
    category: "Furniture",
    price: "₹4,800",
    gst: "18%",
    stock: 3,
    unit: "Pcs",
  },
  {
    id: "P-2006",
    name: "Rice 25kg Bag",
    sku: "GRC-RIC-25",
    category: "Grocery",
    price: "₹1,450",
    gst: "0%",
    stock: 0,
    unit: "Bag",
  },
];

export const categories = [
  { id: "CAT-1", name: "Medicines", products: 128, gstDefault: "12%" },
  { id: "CAT-2", name: "Garments", products: 84, gstDefault: "5%" },
  { id: "CAT-3", name: "Electrical", products: 42, gstDefault: "18%" },
  { id: "CAT-4", name: "Hardware", products: 210, gstDefault: "18%" },
  { id: "CAT-5", name: "Furniture", products: 36, gstDefault: "18%" },
  { id: "CAT-6", name: "Grocery", products: 190, gstDefault: "0%" },
];

export const businessProfiles = [
  {
    id: "B-1",
    name: "Sharma Retail Store",
    gstin: "27ABCDE1234F1Z5",
    type: "Retail",
    city: "Mumbai",
    active: true,
  },
  {
    id: "B-2",
    name: "Sharma Wholesale",
    gstin: "27ABCDE1234F2Z4",
    type: "Wholesale",
    city: "Mumbai",
    active: false,
  },
];
