
"""Harden invoice engine

Revision ID: 20260721_harden_invoice_engine
Revises: 20260721_add_invoice_payment_tables
Create Date: 2026-07-21 21:55:00.000000

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260721_harden_invoice_engine'
down_revision: Union[str, None] = '20260721_add_invoice_payment_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.add_column('invoices', sa.Column('cancelled_by', sa.UUID(), nullable=True))
    op.add_column('invoices', sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('invoices', sa.Column('cancellation_reason', sa.String(length=1000), nullable=True))
    op.create_foreign_key(op.f('fk_invoices_updated_by_users'), 'invoices', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(op.f('fk_invoices_cancelled_by_users'), 'invoices', 'users', ['cancelled_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_invoices_cancelled_by_users'), 'invoices', type_='foreignkey')
    op.drop_constraint(op.f('fk_invoices_updated_by_users'), 'invoices', type_='foreignkey')
    op.drop_column('invoices', 'cancellation_reason')
    op.drop_column('invoices', 'cancelled_at')
    op.drop_column('invoices', 'cancelled_by')
    op.drop_column('invoices', 'updated_by')
    # ### end Alembic commands ###
